name: cd

on:
  push:
    branches: [main]
    paths: [rasterisation/**]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    defaults:
      run:
        working-directory: rasterisation

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Build
        run: |
          npm install
          npm run build:gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: rasterisation/dist
